config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }
  validates :content, presence: true
  validates :restaurant, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def index         # GET /restaurants
    @restaurants = Restaurant.all
  end

  def show          # GET /restaurants/:id
    # @restaurants = Restaurant.find(params[:id])
  end

  def new           # GET /restaurants/new
    @restaurant = Restaurant.new
  end

  def create        # POST /restaurants
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  # def edit       # GET /restaurants/:id/edit
  #   # @restaurant = Restaurant.find(params[:id])
  # end

  # def update        # PATCH /restaurants/:id
  #   # @restaurant = Restaurant.find(params[:id])
  #   @restaurant.update(restaurant_params)

  #   redirect_to restaurant_path(@restaurant)
  # end

  # def destroy       # DELETE /restaurants/:id
  #   # @restaurant = Restaurant.find(params[:id])
  #   @restaurant.destroy

  #   # no need for app/views/restaurants/destroy.html.erb
  #   redirect_to restaurants_path
  # end

  private

  def restaurant_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # we need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to asssociate review with corresponding restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>RailsYelpMvp</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1> YELP MVP </h1>

<div>
  <%= link_to "Add restaurant", new_restaurant_path %>
</div>


<% @restaurants.each do |restaurant| %>
  <div>
    <%= link_to restaurant.name, restaurant_path(restaurant), class: "btn btn-primary"%>
  </div>
<% end %>

app/views/restaurants/new.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- [...] all the fields -->
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.select :category, ['french', 'italian', 'belgian', 'japanese', 'chinese'] %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/show.html.erb
<div>
  <h1> <%= @restaurant.name.upcase %> RESTAURANT</h1>
</div>

<div>
  <ul>
    <li>Address: <%= @restaurant.address %></li>
    <li>Phone Number:<%= @restaurant.phone_number %></li>
    <li>Category: <%= @restaurant.category %></li>
  </ul>
</div>

<div>
  <%= link_to "Add comment", new_restaurant_review_path(@restaurant) %>
</div>

<div>
  <p> <% @restaurant.reviews.each do |review|%>
    <%= review.content %>
    <%= review.rating %>
    <% end %>
  </p>
</div>

<div>
  <br>
  <%= link_to "Back to list", restaurants_path %>
</div>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <% if @review.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, rows: 5, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :rating %>
    <%= f.text_area :rating, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>

<% end %>